version: "3"
services:
  www:
    build: .
    container_name: app_www
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html/
    links:
      - db
    networks:
      - default
    depends_on:
      - db
  db:
    image: mysql
    container_name: app_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: banco
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    links:
      - db:db
    ports:
      - 8002:80
    environment:
      MYSQL_ROOT_PASSWORD: 12
